# Generated by Django 3.0.8 on 2020-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=50)),
                ('lorganisation', models.CharField(max_length=50)),
                ('lemail', models.EmailField(max_length=254)),
                ('lphone', models.IntegerField(max_length=12)),
                ('lsourceoflead', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('sfirsttname', models.CharField(max_length=50)),
                ('slastname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
                ('sphone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
