# Generated by Django 3.0.8 on 2020-07-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='sfirsttname',
            new_name='sfirstname',
        ),
    ]
